# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
#mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
loaderVersion="${loader_version_range}"
issueTrackerURL=""
license="MIT"
[[mods]]
modId="jeimultiblocks"
version="${version}"
displayName="EMI Multiblocks"
description="EMI support for Immersive Engineering Multiblocks"
authors="sguest, pengythegamer"
credits="The Immersive Engineering team for a great base mod and source of sample code"

[[dependencies.jeimultiblocks]]
    modId="forge"
    mandatory=true
    versionRange="${loader_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.jeimultiblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.jeimultiblocks]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="[${ie_version},)"
    ordering="BEFORE"
    side="BOTH"